language: go

go:
  - "1.11.x"
  - "1.12.x"

os:
  - linux
  - osx

env:
  global:
    - GO111MODULE=on

go_import_path: github.com/myitcv/vbash

# Add this before_install until we have a definitive resolution on
# https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/2
before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

install: "echo no install step required"

script:
  - go test ./...
  - go mod tidy
  - go list all > /dev/null # https://github.com/golang/go/issues/27868#issuecomment-431413621
  - diff <(echo -n) <(gofmt -d .)
  - test -z "$(git status --porcelain)" || (git status; git diff; false)
